# Generated by Django 5.2.12 on 2026-03-21 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0002_agency_expand_stage_35'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликован'), ('archived', 'В архиве')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликован')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации')),
                ('deal_type', models.CharField(choices=[('sale', 'Продажа')], db_index=True, default='sale', max_length=10, verbose_name='Тип сделки')),
                ('property_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('land', 'Участок'), ('commercial', 'Коммерция')], db_index=True, max_length=20, verbose_name='Тип недвижимости')),
                ('market_type', models.CharField(blank=True, choices=[('new_building', 'Новостройка'), ('secondary', 'Вторичка'), ('other', 'Иное')], max_length=20, null=True, verbose_name='Рынок')),
                ('title_generated', models.CharField(blank=True, max_length=300, verbose_name='Заголовок (авто)')),
                ('slug', models.SlugField(max_length=320, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Старая цена')),
                ('currency', models.CharField(choices=[('rub', '₽'), ('usd', '$'), ('eur', '€')], default='rub', max_length=3, verbose_name='Валюта')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Улица')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='Номер дома')),
                ('public_address_text', models.CharField(blank=True, max_length=300, verbose_name='Публичный адрес')),
                ('hide_exact_address', models.BooleanField(default=False, verbose_name='Скрыть точный адрес')),
                ('public_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Публичная широта')),
                ('public_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Публичная долгота')),
                ('real_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Реальная широта')),
                ('real_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Реальная долгота')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('phone_views_count', models.PositiveIntegerField(default=0, verbose_name='Показы телефона')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='agencies.agency', verbose_name='Агентство')),
                ('assigned_realtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный риэлтор')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='locations.city', verbose_name='Город')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='locations.district', verbose_name='Район')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='locations.neighborhood', verbose_name='Микрорайон')),
                ('residential_complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='locations.residentialcomplex', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'is_published'], name='properties__status_6c6bfe_idx'), models.Index(fields=['property_type', 'deal_type'], name='properties__propert_c07b56_idx'), models.Index(fields=['city', 'district'], name='properties__city_id_ba8598_idx'), models.Index(fields=['price'], name='properties__price_32e7c2_idx')],
            },
        ),
    ]
