# Generated by Django 5.2.12 on 2026-03-24 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='Количество комнат')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Общая площадь (м²)')),
                ('living_area', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Жилая площадь (м²)')),
                ('kitchen_area', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Площадь кухни (м²)')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('total_floors', models.PositiveSmallIntegerField(verbose_name='Этажей в доме')),
                ('renovation_type', models.CharField(blank=True, choices=[('without', 'Без ремонта'), ('cosmetic', 'Косметический'), ('euro', 'Евроремонт'), ('designer', 'Дизайнерский')], max_length=32, null=True, verbose_name='Ремонт')),
                ('bathroom_type', models.CharField(blank=True, choices=[('combined', 'Совмещённый'), ('separate', 'Раздельный'), ('multiple', 'Несколько')], max_length=32, null=True, verbose_name='Санузел')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_details', to='properties.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Квартира — детали',
                'verbose_name_plural': 'Квартиры — детали',
            },
        ),
    ]
