# Generated by Django 5.2.12 on 2026-03-24 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_apartmentdetails_fields_and_add_balcony_loggia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house_area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь дома (м²)')),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь участка')),
                ('floors_total', models.PositiveSmallIntegerField(verbose_name='Этажей')),
                ('heating_type', models.CharField(blank=True, choices=[('central', 'Центральное'), ('autonomous', 'Автономное'), ('electric', 'Электрическое'), ('none', 'Отсутствует')], max_length=32, null=True, verbose_name='Отопление')),
                ('has_gas', models.BooleanField(default=False, verbose_name='Есть газ')),
                ('has_water', models.BooleanField(default=False, verbose_name='Есть вода')),
                ('has_sewerage', models.BooleanField(default=False, verbose_name='Есть канализация')),
                ('has_electricity', models.BooleanField(default=False, verbose_name='Есть электричество')),
                ('building_type', models.CharField(blank=True, choices=[('brick', 'Кирпич'), ('panel', 'Панель'), ('monolith', 'Монолит'), ('wood', 'Дерево'), ('foam_block', 'Пеноблок'), ('other', 'Иное')], max_length=32, null=True, verbose_name='Тип дома')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_details', to='properties.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Дом — детали',
                'verbose_name_plural': 'Дома — детали',
            },
        ),
    ]
