# Generated by Django 5.2.12 on 2026-03-24 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_housedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandPlotDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь участка')),
                ('land_category', models.CharField(blank=True, choices=[('izhs', 'ИЖС'), ('snt', 'СНТ'), ('dnp', 'ДНП'), ('farm', 'Фермерское хозяйство'), ('industrial', 'Промышленность'), ('other', 'Иное')], max_length=32, null=True, verbose_name='Категория земли')),
                ('permitted_use', models.CharField(blank=True, choices=[('residential', 'Жилое строительство'), ('garden', 'Садоводство'), ('farming', 'Фермерство'), ('commercial', 'Коммерческое использование'), ('other', 'Иное')], max_length=32, null=True, verbose_name='Разрешенное использование')),
                ('has_gas', models.BooleanField(default=False, verbose_name='Есть газ')),
                ('has_water', models.BooleanField(default=False, verbose_name='Есть вода')),
                ('has_electricity', models.BooleanField(default=False, verbose_name='Есть электричество')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_plot_details', to='properties.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Участок — детали',
                'verbose_name_plural': 'Участки — детали',
            },
        ),
    ]
