# Generated by Django 5.2.12 on 2026-03-24 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_landplotdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial_type', models.CharField(blank=True, choices=[('office', 'Офис'), ('retail', 'Торговая площадь'), ('warehouse', 'Склад'), ('production', 'Производство'), ('free_purpose', 'Свободного назначения'), ('catering', 'Общественное питание')], max_length=32, null=True, verbose_name='Тип коммерции')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Общая площадь (м²)')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('floors_total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этажей в здании')),
                ('entrance_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Тип входа')),
                ('parking_spaces', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Парковочных мест')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_details', to='properties.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Коммерция — детали',
                'verbose_name_plural': 'Коммерция — детали',
            },
        ),
    ]
