# Generated by Django 5.2.12 on 2026-03-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_commercialdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=320, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
