# Generated by Django 5.2.12 on 2026-03-27 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_file', models.FileField(upload_to='properties/photos/', verbose_name='Исходный файл')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('mime_type', models.CharField(blank=True, max_length=127, verbose_name='MIME-тип')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Фото объекта',
                'verbose_name_plural': 'Фото объектов',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
