# Generated by Django 5.2 — align PropertyPhoto with project ImageField usage

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_propertyphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyphoto",
            name="original_file",
            field=models.ImageField(
                upload_to="properties/photos/",
                verbose_name="Исходный файл",
            ),
        ),
    ]
