# Generated by Django 5.2.12 on 2026-03-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_propertyphoto_original_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyphoto',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='properties/photos/large/', verbose_name='Крупное изображение'),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='properties/photos/medium/', verbose_name='Среднее изображение'),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='properties/photos/thumb/', verbose_name='Миниатюра'),
        ),
    ]
