# Generated by Django 5.2.12 on 2026-03-27 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_propertyphoto_derived_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('vk', 'VK'), ('rutube', 'RuTube')], max_length=16, verbose_name='Платформа')),
                ('video_url', models.URLField(max_length=2048, verbose_name='Ссылка на видео')),
                ('embed_url', models.URLField(max_length=2048, verbose_name='Ссылка для встраивания')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Видео объекта',
                'verbose_name_plural': 'Видео объектов',
                'ordering': ['id'],
            },
        ),
    ]
