# Generated by Django 5.2.12 on 2026-03-27 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_propertyvideo'),
        ('users', '0002_realtorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(max_length=255, verbose_name='Имя контакта')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('phone_masked', models.CharField(blank=True, max_length=64, verbose_name='Телефон (маскированный)')),
                ('show_phone_enabled', models.BooleanField(default=False, verbose_name='Показ телефона включён')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='properties.property', verbose_name='Объект недвижимости')),
                ('realtor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_contacts', to='users.realtorprofile', verbose_name='Профиль риэлтора')),
            ],
            options={
                'verbose_name': 'Контакт объекта',
                'verbose_name_plural': 'Контакты объектов',
                'ordering': ['id'],
            },
        ),
    ]
