# Generated by Django 5.2.12 on 2026-03-29 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_propertycontact'),
        ('users', '0002_realtorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRevealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('revealed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время раскрытия')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_reveal_logs', to='properties.property', verbose_name='Объект недвижимости')),
                ('realtor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_reveal_logs', to='users.realtorprofile', verbose_name='Профиль риэлтора')),
            ],
            options={
                'verbose_name': 'Лог раскрытия телефона',
                'verbose_name_plural': 'Логи раскрытия телефона',
                'ordering': ['-revealed_at'],
            },
        ),
    ]
