# Generated by Django 5.2.12

from django.db import migrations, models


def recompute_property_slugs(apps, schema_editor):
    from properties.models import Property

    # Не подтягивать поля, добавленные миграциями после 0014 — колонок ещё нет в БД.
    qs = Property.objects.defer("crm_property_id").select_related(
        "city",
        "district",
        "apartment_details",
        "house_details",
        "land_plot_details",
        "commercial_details",
    )
    for prop in qs.iterator(chunk_size=200):
        new_slug = prop.build_generated_slug()
        if new_slug:
            Property.objects.filter(pk=prop.pk).update(slug=new_slug)


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0013_phonereveallog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="slug",
            field=models.SlugField(
                blank=True,
                db_index=True,
                max_length=320,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.RunPython(recompute_property_slugs, migrations.RunPython.noop),
    ]
