# Generated by Django 5.2.12 on 2026-04-03 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_expand_stage_35'),
        ('properties', '0014_property_slug_latin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(upload_to='imports/jobs/', verbose_name='Файл источника')),
                ('source_format', models.CharField(choices=[('csv', 'CSV'), ('xml', 'XML')], db_index=True, max_length=8, verbose_name='Формат')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обработка'), ('completed', 'Завершён'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('field_mapping', models.JSONField(default=dict, help_text='JSON: внешнее имя → внутреннее поле, напр. {"Price": "price"}.', verbose_name='Сопоставление полей')),
                ('error_summary', models.TextField(blank=True, verbose_name='Сводка ошибок (задача)')),
                ('row_count_total', models.PositiveIntegerField(default=0, verbose_name='Всего строк')),
                ('row_count_created', models.PositiveIntegerField(default=0, verbose_name='Создано')),
                ('row_count_skipped_duplicate', models.PositiveIntegerField(default=0, verbose_name='Пропущено (дубликат)')),
                ('row_count_error', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='agencies.agency', verbose_name='Агентство')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Импорт — задача',
                'verbose_name_plural': 'Импорт — задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_index', models.PositiveIntegerField(help_text='0-based порядок в файле.', verbose_name='Индекс строки')),
                ('external_id', models.CharField(blank=True, max_length=255, verbose_name='Внешний идентификатор')),
                ('raw_snapshot', models.JSONField(default=dict, verbose_name='Снимок данных (после маппинга)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('created', 'Создан объект'), ('skipped_duplicate', 'Пропуск (дубликат)'), ('error', 'Ошибка')], db_index=True, default='pending', max_length=24, verbose_name='Статус')),
                ('dedup_outcome', models.CharField(choices=[('none', '—'), ('exact_match', 'Точное совпадение (кандидат)')], default='none', max_length=24, verbose_name='Итог дедупликации')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('duplicate_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_duplicate_hits', to='properties.property', verbose_name='Кандидат дубликата')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_items', to='properties.property', verbose_name='Созданный объект')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='properties.importjob', verbose_name='Задача импорта')),
            ],
            options={
                'verbose_name': 'Импорт — строка',
                'verbose_name_plural': 'Импорт — строки',
                'ordering': ['job', 'row_index'],
                'indexes': [models.Index(fields=['job', 'row_index'], name='properties__job_id_e207ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'row_index'), name='import_item_unique_job_row_index')],
            },
        ),
    ]
