# Generated by Django 5.2.12 on 2026-04-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_import_job_and_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvideo',
            name='embed_url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='Ссылка для встраивания'),
        ),
    ]
