# Generated by Django 5.2.12 on 2026-06-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_property_crm_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Полное описание'),
        ),
    ]
