# Generated by Django 5.2.12 on 2026-06-27 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_neighborhood_options'),
        ('properties', '0019_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='locations.neighborhood', verbose_name='Микрорайон / Населённый пункт'),
        ),
    ]
