# Generated by Django 5.2.12 on 2026-06-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_alter_property_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_type',
            field=models.CharField(blank=True, choices=[('office', 'Офис'), ('retail', 'Торговая площадь'), ('warehouse', 'Склад'), ('production', 'Производство'), ('free_purpose', 'Свободного назначения'), ('catering', 'Общественное питание'), ('hotel', 'Гостиница'), ('guesthouse', 'Гостевой дом')], max_length=32, null=True, verbose_name='Тип коммерции'),
        ),
    ]
