# Generated by Django 5.2.12 on 2026-06-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_alter_commercialdetails_commercial_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentdetails',
            name='floors_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этажей в доме'),
        ),
    ]
