# Generated by Django 5.2.12 on 2026-06-29 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_district_type_drop_is_urban'),
        ('properties', '0022_alter_apartmentdetails_floors_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.district', verbose_name='Район'),
        ),
    ]
