# Generated by Django 5.2.12 on 2026-07-03 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_alter_property_city_alter_property_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата изменения')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Изменение цены',
                'verbose_name_plural': 'История цены',
                'ordering': ['changed_at', 'id'],
                'indexes': [models.Index(fields=['property', 'changed_at'], name='properties__propert_b65315_idx')],
            },
        ),
    ]
