# Generated by Django 5.2.12 on 2026-07-19 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0006_districtguide'),
        ('properties', '0025_backfill_price_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner_name', models.CharField(max_length=255, verbose_name='ФИО собственника')),
                ('owner_phone', models.CharField(max_length=32, verbose_name='Телефон собственника (только для CRM)')),
                ('description', models.TextField(verbose_name='Описание от собственника')),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('land', 'Участок'), ('commercial', 'Коммерция')], max_length=20, verbose_name='Тип недвижимости')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Примерная площадь (м²)')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество комнат')),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Желаемая цена')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('converted', 'Создан объект'), ('rejected', 'Отклонена')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата конвертации')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_requests', to='locations.city', verbose_name='Город')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_sale_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал объект')),
                ('converted_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_sale_requests', to='properties.property', verbose_name='Созданный объект')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_requests', to='locations.district', verbose_name='Район')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_requests', to='locations.neighborhood', verbose_name='Микрорайон / Населённый пункт')),
            ],
            options={
                'verbose_name': 'Заявка на продажу',
                'verbose_name_plural': 'Заявки на продажу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleRequestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='sale_requests/photos/', verbose_name='Фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('sale_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='submissions.salerequest', verbose_name='Заявка на продажу')),
            ],
            options={
                'verbose_name': 'Фото заявки на продажу',
                'verbose_name_plural': 'Фото заявок на продажу',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='salerequest',
            index=models.Index(fields=['status', '-created_at'], name='submissions_status_559b04_idx'),
        ),
    ]
