# Generated by Django 5.2.12 on 2026-04-03 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='ЧПУ (slug)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=models.SlugField(verbose_name='ЧПУ (slug)'),
        ),
        migrations.AlterField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='locations.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='locations.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='slug',
            field=models.SlugField(verbose_name='ЧПУ (slug)'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residential_complexes', to='locations.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residential_complexes', to='locations.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residential_complexes', to='locations.neighborhood', verbose_name='Микрорайон'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='ЧПУ (slug)'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
