# Generated by Django 5.2.12 on 2026-06-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_created_at_alter_city_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Микрорайон / Населённый пункт', 'verbose_name_plural': 'Микрорайоны / Населённые пункты'},
        ),
    ]
