# Generated by Django 5.2.12 on 2026-06-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_neighborhood_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='is_urban',
            field=models.BooleanField(db_index=True, default=True, help_text='True — городской микрорайон; False — сельский населённый пункт (станица, село, посёлок, хутор).', verbose_name='Городской микрорайон'),
        ),
    ]
