# Generated by Django 5.2.12 on 2026-06-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_neighborhood_is_urban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='is_urban',
        ),
        migrations.AddField(
            model_name='district',
            name='district_type',
            field=models.CharField(choices=[('city_district', 'Городской район (есть микрорайоны)'), ('suburb', 'Пригород / населённый пункт (конечная точка)')], db_index=True, default='city_district', max_length=20, verbose_name='Тип района'),
        ),
    ]
