# Generated by Django 5.2.12 on 2026-07-18 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_district_type_drop_is_urban'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(allow_unicode=True, max_length=320, unique=True, verbose_name='ЧПУ (slug)')),
                ('excerpt', models.CharField(max_length=500, verbose_name='Анонс')),
                ('body', models.TextField(verbose_name='Текст')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='districts/covers/', verbose_name='Обложка')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('district', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='locations.district', verbose_name='Район')),
                ('neighborhood', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='locations.neighborhood', verbose_name='Микрорайон / Населённый пункт')),
            ],
            options={
                'verbose_name': 'Гид по району',
                'verbose_name_plural': 'Гиды по районам',
                'ordering': ['-published_at', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('district__isnull', False), ('neighborhood__isnull', True)), models.Q(('district__isnull', True), ('neighborhood__isnull', False)), _connector='OR'), name='districtguide_exactly_one_target')],
            },
        ),
    ]
