# Generated by Django 5.2.12 on 2026-04-03 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('city_property_type', 'Город + тип недвижимости'), ('city_rooms', 'Город + комнатность'), ('city_district', 'Город + район'), ('city_neighborhood', 'Город + микрорайон'), ('residential_complex', 'Жилой комплекс')], db_index=True, max_length=32, verbose_name='Тип страницы')),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('land', 'Участок'), ('commercial', 'Коммерция')], db_index=True, max_length=20, null=True, verbose_name='Тип недвижимости')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Комнат')),
                ('slug', models.SlugField(max_length=320, unique=True, verbose_name='Slug')),
                ('h1', models.CharField(max_length=500, verbose_name='H1')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('meta_description', models.CharField(max_length=320, verbose_name='Meta description')),
                ('seo_text', models.TextField(verbose_name='SEO-текст')),
                ('is_indexable', models.BooleanField(db_index=True, default=True, verbose_name='Индексировать')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_pages', to='locations.city', verbose_name='Город')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_pages', to='locations.district', verbose_name='Район')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_pages', to='locations.neighborhood', verbose_name='Микрорайон')),
                ('residential_complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_pages', to='locations.residentialcomplex', verbose_name='Жилой комплекс')),
            ],
            options={
                'verbose_name': 'SEO-страница',
                'verbose_name_plural': 'SEO-страницы',
                'ordering': ['city', 'page_type', 'slug'],
            },
        ),
    ]
