# Generated by Django 5.2.12 on 2026-04-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial_seo_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seopage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='h1',
            field=models.CharField(max_length=500, verbose_name='Заголовок H1'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='meta_description',
            field=models.CharField(max_length=320, verbose_name='Meta description (описание)'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='slug',
            field=models.SlugField(max_length=320, unique=True, verbose_name='ЧПУ (slug)'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Заголовок (title)'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
