# Generated by Django 5.2.12 on 2026-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='owners/photos/', verbose_name='Фото')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Собственник',
                'verbose_name_plural': 'Собственники',
                'ordering': ['full_name', 'id'],
                'indexes': [models.Index(fields=['phone'], name='owners_owne_phone_99e700_idx'), models.Index(fields=['full_name'], name='owners_owne_full_na_d8a6b4_idx')],
            },
        ),
    ]
