# Generated by Django 5.2.12 on 2026-03-29 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0002_agency_expand_stage_35'),
        ('properties', '0012_propertycontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=32, verbose_name='Телефон клиента')),
                ('client_message', models.TextField(blank=True, verbose_name='Сообщение клиента')),
                ('source', models.CharField(choices=[('website', 'Сайт'), ('phone', 'Телефон'), ('crm', 'CRM'), ('other', 'Прочее')], db_index=True, default='website', max_length=32, verbose_name='Источник')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('converted', 'Успешно'), ('lost', 'Отказ')], db_index=True, default='new', max_length=32, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий')], default='normal', max_length=32, verbose_name='Приоритет')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработан')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='agencies.agency', verbose_name='Агентство')),
                ('assigned_realtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный риэлтор')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='properties.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
    ]
