# Generated by Django 5.2.12 on 2026-03-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('called', 'Связан с клиентом'), ('no_answer', 'Нет ответа'), ('recall_later', 'Перезвонить позже'), ('closed', 'Закрыт'), ('rejected', 'Отклонён')], db_index=True, default='new', max_length=32, verbose_name='Статус'),
        ),
    ]
