# Generated by Django 5.2.12 on 2026-03-29 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leadcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('called', 'Связан с клиентом'), ('no_answer', 'Нет ответа'), ('recall_later', 'Перезвонить позже'), ('closed', 'Закрыт'), ('rejected', 'Отклонён')], max_length=32, null=True, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('called', 'Связан с клиентом'), ('no_answer', 'Нет ответа'), ('recall_later', 'Перезвонить позже'), ('closed', 'Закрыт'), ('rejected', 'Отклонён')], max_length=32, verbose_name='Новый статус')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_status_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='leads.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'История статуса лида',
                'verbose_name_plural': 'История статусов лидов',
                'ordering': ['-created_at'],
            },
        ),
    ]
