# Generated by Django 5.0.2 on 2026-04-17 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_leadphonereveallog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Сайт'), ('landing', 'Лендинг'), ('phone', 'Телефон'), ('crm', 'CRM'), ('other', 'Прочее')], db_index=True, default='website', max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('called', 'Связан с клиентом'), ('completed', 'Завершено'), ('no_answer', 'Нет ответа'), ('recall_later', 'Перезвонить позже'), ('closed', 'Закрыт'), ('rejected', 'Отклонён')], db_index=True, default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='leadstatushistory',
            name='new_status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('called', 'Связан с клиентом'), ('completed', 'Завершено'), ('no_answer', 'Нет ответа'), ('recall_later', 'Перезвонить позже'), ('closed', 'Закрыт'), ('rejected', 'Отклонён')], max_length=32, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='leadstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('called', 'Связан с клиентом'), ('completed', 'Завершено'), ('no_answer', 'Нет ответа'), ('recall_later', 'Перезвонить позже'), ('closed', 'Закрыт'), ('rejected', 'Отклонён')], max_length=32, null=True, verbose_name='Предыдущий статус'),
        ),
        migrations.CreateModel(
            name='LeadActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('status_changed', 'Изменение статуса'), ('phone_revealed', 'Раскрытие телефона'), ('note_added', 'Комментарий')], db_index=True, max_length=32, verbose_name='Тип действия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='leads.lead', verbose_name='Лид')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Действие по лиду',
                'verbose_name_plural': 'История действий по лидам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('text', models.TextField(verbose_name='Текст')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'Комментарий к лиду (заметка)',
                'verbose_name_plural': 'Комментарии к лидам (заметки)',
                'ordering': ['-created_at'],
            },
        ),
    ]
