# Generated by Django 5.2.12 on 2026-03-16 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_name', models.CharField(blank=True, max_length=255, verbose_name='public name')),
                ('public_phone', models.CharField(blank=True, max_length=32, verbose_name='public phone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='realtors/photos/', verbose_name='photo')),
                ('short_bio', models.TextField(blank=True, verbose_name='short bio')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtor_profiles', to='agencies.agency', verbose_name='agency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'realtor profile',
                'verbose_name_plural': 'realtor profiles',
            },
        ),
    ]
