# Generated by Django 5.2.12 on 2026-04-03 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_alter_agency_options_alter_agency_created_at_and_more'),
        ('users', '0002_realtorprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtorprofile',
            options={'verbose_name': 'Профиль риэлтора', 'verbose_name_plural': 'Профили риэлторов'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='realtorprofile',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtor_profiles', to='agencies.agency', verbose_name='Агентство'),
        ),
        migrations.AlterField(
            model_name='realtorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='realtorprofile',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='realtorprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='realtors/photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='realtorprofile',
            name='public_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Публичное имя'),
        ),
        migrations.AlterField(
            model_name='realtorprofile',
            name='public_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Публичный телефон'),
        ),
        migrations.AlterField(
            model_name='realtorprofile',
            name='short_bio',
            field=models.TextField(blank=True, verbose_name='Краткая биография'),
        ),
        migrations.AlterField(
            model_name='realtorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='realtorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Доступ в админку'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Суперадминистратор'), ('admin', 'Администратор'), ('realtor', 'Риэлтор')], default='realtor', max_length=20, verbose_name='Роль'),
        ),
    ]
