# Generated by Django 5.2.12 on 2026-08-08 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_employee_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeactivitylog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs_as_target', to=settings.AUTH_USER_MODEL, verbose_name='Над кем'),
        ),
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=0, verbose_name='Поколение токенов'),
        ),
        migrations.AlterField(
            model_name='employeeactivitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('password_reset', 'Сброс пароля'), ('email_change', 'Смена email')], db_index=True, max_length=32, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='employeeactivitylog',
            name='user',
            field=models.ForeignKey(help_text='Кто выполнил действие.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
