# Generated by Django 5.2.12 on 2026-08-08 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employeeactivitylog_target_user_user_token_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeactivitylog',
            name='attempted_email',
            field=models.CharField(blank=True, max_length=254, verbose_name='Введённый email'),
        ),
        migrations.AddField(
            model_name='employeeactivitylog',
            name='reason',
            field=models.CharField(blank=True, choices=[('bad_credentials', 'Неверные данные'), ('locked', 'Аккаунт заблокирован'), ('throttled', 'Слишком много попыток')], max_length=32, verbose_name='Причина'),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Неудачных попыток входа подряд'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Заблокирован до'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Требуется смена пароля'),
        ),
        migrations.AlterField(
            model_name='employeeactivitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('password_reset', 'Сброс пароля'), ('email_change', 'Смена email'), ('login_failed', 'Неудачный вход'), ('unlock', 'Снятие блокировки'), ('sessions_terminated', 'Завершение сессий')], db_index=True, max_length=32, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='employeeactivitylog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Кто выполнил действие.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
